---

aws_region: "ap-southeast-2"
aws_profile: "{{ aws_profile_env }}"
vpc_id: "{{ vpc_id_env }}"


sg_cluster_name: "{{ cluster_name }}"
sg_description: "{{ cluster_name }} security rules"
sg_vpc_id: "{{ vpc_id }}"
sg_state: present
sg_rules:
  - proto: tcp
    from_port: 22
    to_port: 22
    cidr_ip: "0.0.0.0/0"
  - proto: tcp     # for the ECS NGinx proxy
    from_port: 80
    to_port: 80
    group_name: "10.100.0.0/16" # see below to only Authorize traffic from ELB
  # - proto: tcp     # for the ECS NGinx proxy
  #   from_port: 80
  #   to_port: 80
  #   group_name: "cluster_name-service_name-lb" # change to your ELB security group name
  #   group_desc: "Dummy description"

  - proto: all     # Authorize all the internal traffic between your machines
    group_name: "{{ sg_cluster_name }}-cluster"

asg_ecs_cluster_name: "{{ cluster_name }}"
asg_launch_config_key_name: "{{ asg_launch_config_key_name_env }}"
asg_launch_config_instance_size: "t2.small"
asg_launch_config_instance_profile_name: "{{ asg_launch_config_instance_profile_name_env }}"
asg_launch_config_assign_public_ip: false
asg_min_size: 0
asg_max_size: 1
asg_desired_capacity: 0
asg_subnets: "{{ asg_subnets_env }}"
asg_vpc_id: "{{ vpc_id }}"
asg_additional_security_groups: "{{ asg_additional_security_groups_env | default([]) }}"


ecs_cluster_name: "{{ cluster_name }}"
