aws_region: "ap-southeast-2"
aws_profile: "{{ aws_profile_env }}"

# ECR Role Specific
ecr_create: "{{ ecr_create_env | default(false) }}"
ecr_repository_name: "{{ service_name }}"
ecr_additional_aws_account_list: []

# ECS Role Specific
ecs_service_desired_account: "{{ ecs_service_desired_count_env }}"
ecs_cluster_name: "{{ cluster_name }}"
ecs_service_name: "{{ service_name }}"
ecs_taskdefinition_containers:
  - name: "{{ ecs_service_name }}"
    essential: true
    image: "{{ image_env }}"
    memoryReservation: "{{ memory_reservation_env }}"
    logConfiguration:
      logDriver: "awslogs"
      options: {
        "awslogs-group": "/airflow/{{ service_name }}",
        "awslogs-region": "ap-southeast-2"
      }
    environment:
      - name: LOAD_EX
        value: "{{ load_ex_env }}"
      - name: FERNET_KEY
        value: "46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho="
      - name: EXECUTOR
        value: "Celery"
      - name: AIRFLOW__CORE__EXECUTOR
        value: "CeleryExecutor"
      - name: POSTGRES_USER
        value: "{{ postgres_user_env }}"
      - name: POSTGRES_PASSWORD
        value: "{{ postgres_password_env }}"
      - name: POSTGRES_HOST
        value: "{{ postgres_host_env }}"
      - name: POSTGRES_PORT
        value: "5432"
      - name: POSTGRES_DB
        value: "{{ postgres_db_env }}"
      - name: REDIS_HOST
        value: "{{ redis_host_env }}"
      - name: REDIS_PORT
        value: "6379"
      - name: AIRFLOW__CORE__REMOTE_LOG_CONN_ID
        value: "S3_LOGGING"
      - name: AIRFLOW__CORE__REMOTE_LOGGING
        value: "True"
      - name: AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER
        value: "{{ airflow_conn_s3_logging_env }}"
      - name: AIRFLOW_CONN_S3_LOGGING
        value: ""
      - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
        value: "postgresql+psycopg2://{{ postgres_user_env }}:{{ postgres_password_env }}@{{ postgres_host_env }}:5432/{{ postgres_db_env }}"
      - name: WEBSERVER_HOSTNAME
        value: "{{ webserver_hostname_env }}"
      - name: AIRFLOW__WEBSERVER__BASE_URL
        value: "{{ airflow_webserver_base_url_env }}"
      - name: VARIABLES_FILE
        value: "{{ variables_file_env }}"

    mountPoints:
      - containerPath: /usr/local/airflow/logs
        sourceVolume: "airflow_logs"

    command:
      - flower

    portMappings:
      - containerPort: 5555
        hostPort: 5555
        protocol: tcp

  ecs_deployment_configuration:
    minimum_healthy_percent: 0
    maximum_percent: 200

  ecs_taskdefinition_volumes:
    - name: "airflow_logs"
      host:
        sourcePath: "/efs/airflow_logs"